### PR TITLE
Add Lenovo A6000 Maintainer.

### PR DESCRIPTION
**Pull request by HassanSardar**

### CODE REVIEW

**Comment by BirdmanJ** [comment]
@HassanSardar Add here too res/xml/device_maintainers.xml

**Comment by HassanSardar** [comment]
@BirdmanJ  Thanks, already done.

**Comment by BirdmanJ** [comment]
@HassanSardar Welcome the team

**Comment by HassanSardar** [comment]
@BirdmanJ Thank you! I'm honored. :)

**Pull request merged**
